# Generated by Django 2.0.1 on 2018-03-19 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='部门名称')),
                ('addr', models.CharField(max_length=128, verbose_name='办公地址')),
                ('city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='HostRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.CharField(choices=[('checked', '已修改'), ('late', '未修改'), ('noshow', '无需修改'), ('leave_early', '任务撤销')], default='checked', max_length=64, verbose_name='修改纪录')),
                ('score', models.IntegerField(choices=[(100, 'A+'), (90, 'A'), (85, 'B+'), (80, 'B'), (70, 'B-'), (60, 'C+'), (50, 'C'), (40, 'C-'), (0, 'D'), (-1, 'N/A'), (-100, 'COPY'), (-1000, 'FAIL')], default=-1, verbose_name='此次修改任务完成进度')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': '服务器主机修改纪录',
                'verbose_name': '服务器主机修改纪录',
            },
        ),
        migrations.CreateModel(
            name='HostServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True, verbose_name='主机ip')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('stu_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机编号')),
                ('source_type', models.CharField(choices=[('yunwei', '运维人员创建'), ('referral', '内部冗余备机'), ('chengdu', '成都创建'), ('guanwu', '关务开发创建'), ('qingsuan', '清算开发创建'), ('dbserver', '数据库开发创建'), ('others', '其它')], default='yunwei', max_length=64, verbose_name='主机创建来源')),
                ('server_type', models.CharField(choices=[('product', '生产环境'), ('pre', '域生产环境'), ('test', '测试环境')], default='test', max_length=64, verbose_name='服务器环境类型')),
                ('server_memo', models.TextField(help_text='主机需创建前的大概情况,主机信息备注等...', verbose_name='主机需创建前内容详情')),
                ('status', models.CharField(choices=[('signed', '运行中'), ('unregistered', '宕机'), ('working', '运行中'), ('down-off', '宕机')], default='unregistered', help_text='选择服务器主机此时的状态', max_length=64, verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='提需求日期')),
            ],
        ),
        migrations.CreateModel(
            name='HostServer01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True, verbose_name='主机ip')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('stu_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机编号')),
                ('source_type', models.CharField(choices=[('yunwei', '运维人员创建'), ('referral', '内部冗余备机'), ('chengdu', '成都创建'), ('guanwu', '关务开发创建'), ('qingsuan', '清算开发创建'), ('dbserver', '数据库开发创建'), ('others', '其它')], default='yunwei', max_length=64, verbose_name='主机创建来源')),
                ('server_type', models.CharField(choices=[('product', '生产环境'), ('pre', '域生产环境'), ('test', '测试环境')], default='test', max_length=64, verbose_name='服务器环境类型')),
                ('server_memo', models.TextField(help_text='主机需创建前的大概情况,主机信息备注等...', verbose_name='主机需创建前内容详情')),
                ('status', models.CharField(choices=[('signed', '运行中'), ('unregistered', '宕机'), ('working', '运行中'), ('down-off', '宕机')], default='unregistered', help_text='选择服务器主机此时的状态', max_length=64, verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='提需求日期')),
            ],
        ),
        migrations.CreateModel(
            name='HostServer02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True, verbose_name='主机ip')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('stu_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机编号')),
                ('source_type', models.CharField(choices=[('yunwei', '运维人员创建'), ('referral', '内部冗余备机'), ('chengdu', '成都创建'), ('guanwu', '关务开发创建'), ('qingsuan', '清算开发创建'), ('dbserver', '数据库开发创建'), ('others', '其它')], default='yunwei', max_length=64, verbose_name='主机创建来源')),
                ('server_type', models.CharField(choices=[('product', '生产环境'), ('pre', '域生产环境'), ('test', '测试环境')], default='test', max_length=64, verbose_name='服务器环境类型')),
                ('server_memo', models.TextField(help_text='主机需创建前的大概情况,主机信息备注等...', verbose_name='主机需创建前内容详情')),
                ('status', models.CharField(choices=[('signed', '运行中'), ('unregistered', '宕机'), ('working', '运行中'), ('down-off', '宕机')], default='unregistered', help_text='选择服务器主机此时的状态', max_length=64, verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='提需求日期')),
            ],
        ),
        migrations.CreateModel(
            name='HostServer03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True, verbose_name='主机ip')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('stu_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机编号')),
                ('source_type', models.CharField(choices=[('yunwei', '运维人员创建'), ('referral', '内部冗余备机'), ('chengdu', '成都创建'), ('guanwu', '关务开发创建'), ('qingsuan', '清算开发创建'), ('dbserver', '数据库开发创建'), ('others', '其它')], default='yunwei', max_length=64, verbose_name='主机创建来源')),
                ('server_type', models.CharField(choices=[('product', '生产环境'), ('pre', '域生产环境'), ('test', '测试环境')], default='test', max_length=64, verbose_name='服务器环境类型')),
                ('server_memo', models.TextField(help_text='主机需创建前的大概情况,主机信息备注等...', verbose_name='主机需创建前内容详情')),
                ('status', models.CharField(choices=[('signed', '运行中'), ('unregistered', '宕机'), ('working', '运行中'), ('down-off', '宕机')], default='unregistered', help_text='选择服务器主机此时的状态', max_length=64, verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='提需求日期')),
            ],
        ),
        migrations.CreateModel(
            name='HostServer04',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True, verbose_name='主机ip')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('stu_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机编号')),
                ('source_type', models.CharField(choices=[('yunwei', '运维人员创建'), ('referral', '内部冗余备机'), ('chengdu', '成都创建'), ('guanwu', '关务开发创建'), ('qingsuan', '清算开发创建'), ('dbserver', '数据库开发创建'), ('others', '其它')], default='yunwei', max_length=64, verbose_name='主机创建来源')),
                ('server_type', models.CharField(choices=[('product', '生产环境'), ('pre', '域生产环境'), ('test', '测试环境')], default='test', max_length=64, verbose_name='服务器环境类型')),
                ('server_memo', models.TextField(help_text='主机需创建前的大概情况,主机信息备注等...', verbose_name='主机需创建前内容详情')),
                ('status', models.CharField(choices=[('signed', '运行中'), ('unregistered', '宕机'), ('working', '运行中'), ('down-off', '宕机')], default='unregistered', help_text='选择服务器主机此时的状态', max_length=64, verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='提需求日期')),
            ],
        ),
        migrations.CreateModel(
            name='HostServer05',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True, verbose_name='主机ip')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('stu_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机编号')),
                ('source_type', models.CharField(choices=[('yunwei', '运维人员创建'), ('referral', '内部冗余备机'), ('chengdu', '成都创建'), ('guanwu', '关务开发创建'), ('qingsuan', '清算开发创建'), ('dbserver', '数据库开发创建'), ('others', '其它')], default='yunwei', max_length=64, verbose_name='主机创建来源')),
                ('server_type', models.CharField(choices=[('product', '生产环境'), ('pre', '域生产环境'), ('test', '测试环境')], default='test', max_length=64, verbose_name='服务器环境类型')),
                ('server_memo', models.TextField(help_text='主机需创建前的大概情况,主机信息备注等...', verbose_name='主机需创建前内容详情')),
                ('status', models.CharField(choices=[('signed', '运行中'), ('unregistered', '宕机'), ('working', '运行中'), ('down-off', '宕机')], default='unregistered', help_text='选择服务器主机此时的状态', max_length=64, verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='提需求日期')),
            ],
        ),
        migrations.CreateModel(
            name='HostServer06',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True, verbose_name='主机ip')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('stu_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机编号')),
                ('source_type', models.CharField(choices=[('yunwei', '运维人员创建'), ('referral', '内部冗余备机'), ('chengdu', '成都创建'), ('guanwu', '关务开发创建'), ('qingsuan', '清算开发创建'), ('dbserver', '数据库开发创建'), ('others', '其它')], default='yunwei', max_length=64, verbose_name='主机创建来源')),
                ('server_type', models.CharField(choices=[('product', '生产环境'), ('pre', '域生产环境'), ('test', '测试环境')], default='test', max_length=64, verbose_name='服务器环境类型')),
                ('server_memo', models.TextField(help_text='主机需创建前的大概情况,主机信息备注等...', verbose_name='主机需创建前内容详情')),
                ('status', models.CharField(choices=[('signed', '运行中'), ('unregistered', '宕机'), ('working', '运行中'), ('down-off', '宕机')], default='unregistered', help_text='选择服务器主机此时的状态', max_length=64, verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='提需求日期')),
            ],
        ),
        migrations.CreateModel(
            name='HostServer07',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True, verbose_name='主机ip')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('stu_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机编号')),
                ('source_type', models.CharField(choices=[('yunwei', '运维人员创建'), ('referral', '内部冗余备机'), ('chengdu', '成都创建'), ('guanwu', '关务开发创建'), ('qingsuan', '清算开发创建'), ('dbserver', '数据库开发创建'), ('others', '其它')], default='yunwei', max_length=64, verbose_name='主机创建来源')),
                ('server_type', models.CharField(choices=[('product', '生产环境'), ('pre', '域生产环境'), ('test', '测试环境')], default='test', max_length=64, verbose_name='服务器环境类型')),
                ('server_memo', models.TextField(help_text='主机需创建前的大概情况,主机信息备注等...', verbose_name='主机需创建前内容详情')),
                ('status', models.CharField(choices=[('signed', '运行中'), ('unregistered', '宕机'), ('working', '运行中'), ('down-off', '宕机')], default='unregistered', help_text='选择服务器主机此时的状态', max_length=64, verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='提需求日期')),
            ],
        ),
        migrations.CreateModel(
            name='HostServer08',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64, unique=True, verbose_name='主机ip')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='联系电话')),
                ('stu_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机编号')),
                ('source_type', models.CharField(choices=[('yunwei', '运维人员创建'), ('referral', '内部冗余备机'), ('chengdu', '成都创建'), ('guanwu', '关务开发创建'), ('qingsuan', '清算开发创建'), ('dbserver', '数据库开发创建'), ('others', '其它')], default='yunwei', max_length=64, verbose_name='主机创建来源')),
                ('server_type', models.CharField(choices=[('product', '生产环境'), ('pre', '域生产环境'), ('test', '测试环境')], default='test', max_length=64, verbose_name='服务器环境类型')),
                ('server_memo', models.TextField(help_text='主机需创建前的大概情况,主机信息备注等...', verbose_name='主机需创建前内容详情')),
                ('status', models.CharField(choices=[('signed', '运行中'), ('unregistered', '宕机'), ('working', '运行中'), ('down-off', '宕机')], default='unregistered', help_text='选择服务器主机此时的状态', max_length=64, verbose_name='状态')),
                ('date', models.DateField(auto_now_add=True, verbose_name='提需求日期')),
            ],
        ),
        migrations.CreateModel(
            name='HostServerTrackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_record', models.TextField(verbose_name='跟踪记录')),
                ('track_date', models.DateTimeField(auto_now_add=True, verbose_name='跟进日期')),
                ('status', models.IntegerField(choices=[(1, '近期无开启计划'), (2, '2个月内开启'), (3, '1个月内开启'), (4, '2周内开启'), (5, '1周内开启'), (6, '2天内开启'), (7, '已开启')], help_text='选择需求服务器此时的状态', verbose_name='状态')),
            ],
            options={
                'verbose_name_plural': '服务器需求主机跟进记录',
                'verbose_name': '服务器需求主机跟进记录',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='服务功能名称')),
                ('dell_server', models.CharField(max_length=64, verbose_name='dell物理机')),
                ('kaixiang_server', models.CharField(max_length=64, verbose_name='凯翔物理机')),
                ('lc_server', models.CharField(max_length=64, verbose_name='浪潮物理机')),
                ('esxi_server', models.CharField(max_length=64, verbose_name='esxi物理机')),
                ('introduction', models.TextField(verbose_name='功能及相关简介')),
            ],
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_type', models.CharField(choices=[('product', '生产环境'), ('pre', '域生产环境'), ('test', '测试环境')], max_length=64, verbose_name='服务器环境类型')),
                ('semester', models.IntegerField(verbose_name='开启服务批次')),
                ('start_date', models.DateField(verbose_name='开服日期')),
                ('drop_date', models.DateField(blank=True, null=True, verbose_name='停服日期')),
            ],
            options={
                'verbose_name_plural': '服务器主机列表',
                'verbose_name': '服务器主机列表',
            },
        ),
        migrations.CreateModel(
            name='ServerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(help_text='此处填写第几次修改或第几天修改应用...,必须为数字', verbose_name='第几次')),
                ('modify_date', models.DateField(auto_now_add=True, verbose_name='修改日期')),
            ],
            options={
                'verbose_name_plural': '服务器功能修改纪录',
                'verbose_name': '服务器功能修改纪录',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='服务器名')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_server_list', '可以查看服务器列表'), ('view_server_info', '可以查看服务器详情'), ('edit_own_server_info', '可以修改自己的查看服务器信息')),
            },
        ),
        migrations.AddField(
            model_name='serverrecord',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='serverrecord',
            name='server_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ServerList', verbose_name='服务应用名称(环境)'),
        ),
        migrations.AddField(
            model_name='serverlist',
            name='manager',
            field=models.ManyToManyField(to='crm.UserProfile', verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='serverlist',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Server', verbose_name='服务环境名称'),
        ),
        migrations.AddField(
            model_name='hostservertrackrecord',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='跟踪人'),
        ),
        migrations.AddField(
            model_name='hostservertrackrecord',
            name='hostserver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.HostServer', verbose_name='服务器主机名称'),
        ),
        migrations.AddField(
            model_name='hostserver08',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='需求人姓名'),
        ),
        migrations.AddField(
            model_name='hostserver08',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此主机是转备份做其它主机备机用,请在此处选择主机名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm.HostServer08', verbose_name='转相关备机'),
        ),
        migrations.AddField(
            model_name='hostserver08',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Server', verbose_name='主机创建需求'),
        ),
        migrations.AddField(
            model_name='hostserver08',
            name='server_list',
            field=models.ManyToManyField(blank=True, to='crm.ServerList', verbose_name='服务应用类型'),
        ),
        migrations.AddField(
            model_name='hostserver07',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='需求人姓名'),
        ),
        migrations.AddField(
            model_name='hostserver07',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此主机是转备份做其它主机备机用,请在此处选择主机名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm.HostServer07', verbose_name='转相关备机'),
        ),
        migrations.AddField(
            model_name='hostserver07',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Server', verbose_name='主机创建需求'),
        ),
        migrations.AddField(
            model_name='hostserver07',
            name='server_list',
            field=models.ManyToManyField(blank=True, to='crm.ServerList', verbose_name='服务应用类型'),
        ),
        migrations.AddField(
            model_name='hostserver06',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='需求人姓名'),
        ),
        migrations.AddField(
            model_name='hostserver06',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此主机是转备份做其它主机备机用,请在此处选择主机名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm.HostServer06', verbose_name='转相关备机'),
        ),
        migrations.AddField(
            model_name='hostserver06',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Server', verbose_name='主机创建需求'),
        ),
        migrations.AddField(
            model_name='hostserver06',
            name='server_list',
            field=models.ManyToManyField(blank=True, to='crm.ServerList', verbose_name='服务应用类型'),
        ),
        migrations.AddField(
            model_name='hostserver05',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='需求人姓名'),
        ),
        migrations.AddField(
            model_name='hostserver05',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此主机是转备份做其它主机备机用,请在此处选择主机名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm.HostServer05', verbose_name='转相关备机'),
        ),
        migrations.AddField(
            model_name='hostserver05',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Server', verbose_name='主机创建需求'),
        ),
        migrations.AddField(
            model_name='hostserver05',
            name='server_list',
            field=models.ManyToManyField(blank=True, to='crm.ServerList', verbose_name='服务应用类型'),
        ),
        migrations.AddField(
            model_name='hostserver04',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='需求人姓名'),
        ),
        migrations.AddField(
            model_name='hostserver04',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此主机是转备份做其它主机备机用,请在此处选择主机名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm.HostServer04', verbose_name='转相关备机'),
        ),
        migrations.AddField(
            model_name='hostserver04',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Server', verbose_name='主机创建需求'),
        ),
        migrations.AddField(
            model_name='hostserver04',
            name='server_list',
            field=models.ManyToManyField(blank=True, to='crm.ServerList', verbose_name='服务应用类型'),
        ),
        migrations.AddField(
            model_name='hostserver03',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='需求人姓名'),
        ),
        migrations.AddField(
            model_name='hostserver03',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此主机是转备份做其它主机备机用,请在此处选择主机名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm.HostServer03', verbose_name='转相关备机'),
        ),
        migrations.AddField(
            model_name='hostserver03',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Server', verbose_name='主机创建需求'),
        ),
        migrations.AddField(
            model_name='hostserver03',
            name='server_list',
            field=models.ManyToManyField(blank=True, to='crm.ServerList', verbose_name='服务应用类型'),
        ),
        migrations.AddField(
            model_name='hostserver02',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='需求人姓名'),
        ),
        migrations.AddField(
            model_name='hostserver02',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此主机是转备份做其它主机备机用,请在此处选择主机名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm.HostServer02', verbose_name='转相关备机'),
        ),
        migrations.AddField(
            model_name='hostserver02',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Server', verbose_name='主机创建需求'),
        ),
        migrations.AddField(
            model_name='hostserver02',
            name='server_list',
            field=models.ManyToManyField(blank=True, to='crm.ServerList', verbose_name='服务应用类型'),
        ),
        migrations.AddField(
            model_name='hostserver01',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='需求人姓名'),
        ),
        migrations.AddField(
            model_name='hostserver01',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此主机是转备份做其它主机备机用,请在此处选择主机名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm.HostServer01', verbose_name='转相关备机'),
        ),
        migrations.AddField(
            model_name='hostserver01',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Server', verbose_name='主机创建需求'),
        ),
        migrations.AddField(
            model_name='hostserver01',
            name='server_list',
            field=models.ManyToManyField(blank=True, to='crm.ServerList', verbose_name='服务应用类型'),
        ),
        migrations.AddField(
            model_name='hostserver',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.UserProfile', verbose_name='需求人姓名'),
        ),
        migrations.AddField(
            model_name='hostserver',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此主机是转备份做其它主机备机用,请在此处选择主机名称', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referraled_who', to='crm.HostServer', verbose_name='转相关备机'),
        ),
        migrations.AddField(
            model_name='hostserver',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Server', verbose_name='主机创建需求'),
        ),
        migrations.AddField(
            model_name='hostserver',
            name='server_list',
            field=models.ManyToManyField(blank=True, to='crm.ServerList', verbose_name='服务应用类型'),
        ),
        migrations.AddField(
            model_name='hostrecord',
            name='server_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.HostServer', verbose_name='主机名'),
        ),
        migrations.AddField(
            model_name='hostrecord',
            name='server_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ServerRecord', verbose_name='第几次修改主机'),
        ),
        migrations.AlterUniqueTogether(
            name='serverrecord',
            unique_together={('server_obj', 'day_num')},
        ),
        migrations.AlterUniqueTogether(
            name='serverlist',
            unique_together={('server', 'server_type', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='hostrecord',
            unique_together={('server_record', 'server_name')},
        ),
    ]
